### ISSUE TITLE
Documentation not accessible 

### ISSUE THREAD

**Issue by luongvo209** [instana/ruby-sensor#110]
Right now the link https://instana.atlassian.net/wiki/display/DOCS/Ruby is not accessible. Logging in Atlassian account results in "Your email address v.....g@gmail.com doesn't have access to instana.atlassian.net".  

I am a bit confused. This is my first time accessing the docs. Is it meant to be private?

**Comment by CodingFabian** [comment]
Thanks @luongvo209 - I have updated the documentation links in the readme:
https://github.com/instana/ruby-sensor/commit/30b6b09dbf86d44024347e2a8da4616271d4938b

**Comment by Adithya-copart** [comment]
@CodingFabian FYI, There are at least two more references to this atlassian URL in `Configuration.MD` and `Troubleshooting.md`

**Comment by CodingFabian** [comment]
thanks @Adithya-copart also fixed those straggles to point to https://docs.instana.io/ecosystem/ruby/
