### ISSUE TITLE
Support for JRuby

### ISSUE THREAD

**Issue by Adithya-copart** [instana/ruby-sensor#142]
Hello,

Are there any plans to support JRuby in the future?

I scanned the repository for any `.c` files and did not find any. I noticed that `Oj` uses native C-extensions apart from `byebug` and `pry-byebug` in development.

Is there a design limitation that would prevent the usage of this gem in JRuby?

I noticed 3 test failures while using stdlib `json` instead of `oj`.
I'll try to dig deeper if there is nothing else that limits the usage in JRuby.

**Comment by Adithya-copart** [comment]
`bin/rake test` [results](https://gist.github.com/Adithya-copart/5cb4264709c83a24977f4e81296c1a23) in a docker container built using `FROM jruby:9.2.7.0-jdk`

**Comment by Adithya-copart** [comment]
I'm hitting the following error after removing the dependency on `oj`.
Looks like the agent scans for the JRuby process name and fails.

```
2019-08-07T20:43:16.668+0000 | ERROR | na-http-thread-1 | Ruby | 131 - com.instana.discovery-ruby - 1.3.0 | Could not find the process RubyProcess . Found 4 possible candidates. 
```
Supporting JRuby in the agent will help us collect metrics efficiently.
I'm happy to try out any workarounds to test in JRuby.

**Comment by pglombardo** [comment]
Hi @Adithya-copart,

Re: json vs. Oj - this should work fine as Oj is a drop in replacement that we used for faster json encoding.

> 58 tests, 12452 assertions, 0 failures, 0 errors, 0 skips
Cool :-)

```
2019-08-06 16:12:40 +0000: Listen loop error: #<IOError: closed stream>
org/jruby/RubyIO.java:3552:in `select'
/usr/local/bundle/gems/puma-4.0.1-java/lib/puma/server.rb:380:in `handle_servers'
/usr/local/bundle/gems/puma-4.0.1-java/lib/puma/server.rb:354:in `block in run'
2019-08-06 16:12:40 +0000: Listen loop error: #<IOError: closed stream>
```
The test suite runs some puma webservers in background threads - this appears to be related to and limited to the test suite.

On the posted error: My guess is that it is unrelated to the gem change.

Since we haven't added official JRuby support, this hasn't been thoroughly tested.  It's possible that that error is transient and eventually resolves on its own.  Could you confirm this?  Do your JRuby processes show up on the dashboard?

**Comment by Adithya-copart** [comment]
@pglombardo Unfortunately, this did not resolve on its own.
https://github.com/instana/ruby-sensor/blob/694b4187ff3bcc3d31b12ef8bd1b75ee197b75d3/lib/instana/agent.rb#L216
It occurs during the above `PUT` call to the agent.

I could not find the relevant code that handles this request in any of the public repositories. I suspect it is private. The agent probably uses the process info in the HTTP call to match against the list of running processes in its host. We're sending the `pid`, `name` and `arguments` in the payload.

I explored changing the process name using `setproctitle` [method](https://ruby-doc.org/core-2.6.2/Process.html#method-c-setproctitle) which is not working in JRuby as expected. The other solution I came across is to use `prctl` via a `LD_PRELOAD` hook to rename the process.

I'm not sure if this approach works but it'll be easy if instana agent supports this jruby process lookup.

**Comment by pglombardo** [comment]
> I could not find the relevant code that handles this request in any of the public repositories. I suspect it is private. The agent probably uses the process info in the HTTP call to match against the list of running processes in its host. We're sending the pid, name and arguments in the payload.

This is correct - the Instana host agent searches the process table for a matching process.  The complexity comes when there are multiple processes with the same command line or in-container pids (like pid 1).  There are steps to properly identify the correct process but obviously this hasn't been tested in JRuby.

Is it possible that you could try this on Linux to confirm?  There we use the /proc filesystem to identify processes on Linux and is more reliable than OSX (without /proc).

**Comment by Adithya-copart** [comment]
@pglombardo The above results are from a docker container using linux.

I was looking into the code and noticed that `@is_linux = (RUBY_PLATFORM =~ /linux/i) ? true : false` always returns false as RUBY_PLATFORM is `java` in this case.

I will update it to `RbConfig::CONFIG['host_os'] == 'linux'` and update the results.

**Comment by Adithya-copart** [comment]
Still see the same error in the agent.

This could be due to the number of arguments we pass, the message `Found 3 possible candidates` is right as we have 3 JRuby processes running with the last 3 arguments different.
```
2019-08-08T17:19:58.300+0000 | ERROR | na-http-thread-3 | Ruby                             | 131 - com.instana.discovery-ruby - 1.3.0 | Could not find the process RubyProcess [pid=31, name=/usr/local/openjdk-8/bin/java, arguments=[-Xmx1024m, -Xms512m, -Xss2048k, ......, -Djruby.shell=/bin/sh, org.jruby.Main, bin/puma, -p, 8080], fd=null, inode=null]. Found 3 possible candidates. 
```

**Comment by Adithya-copart** [comment]
**Updates:** I'm running into issues with the `POST` call that is responsible to report the metrics in the collector. These are the keys in the payload: 
```
[:memory, :thread, :sensorVersion, :ruby_version, :rpl, :framework, :versions, :pid, :fd, :inode, :name, :exec_args] 
```

https://github.com/instana/ruby-sensor/blob/052fc3dc0965605700a75adfd57243a1775cffa3/lib/instana/collector.rb#L47-L88

The `POST` returns `Response:#<Net::HTTPNotFound:0x379ef89c>`. I added additional process info like the `fd` and `inode` to see if it changes the response but it did not.

After leaving the process for a little while, the only logs I see are the following POST calls from the thread and memory collectors:
```
13:16:34 web.1     | D, [2019-08-09T13:16:34.225457 #30] DEBUG -- : Instana: POST->http://<host>:42699/com.instana.plugin.ruby.29760 body:({}) Response:#<Net::HTTPOK:0x4af6e504> body:([])

13:16:34 web.1     | D, [2019-08-09T13:16:34.228226 #30] DEBUG -- : Instana: POST->http://<host>:42699/com.instana.plugin.ruby.29760 body:({"memory":{}}) Response:#<Net::HTTPOK:0x67e72858> body:([])
```

Currently, I'm trying to see why Sinatra/Rack requests are not being reported.

**Comment by pglombardo** [comment]
Nice progress :-)  The metrics will get return 404 responses until the host agent is fully ready to relay the metrics so the 404s are expected for a short period after successful announce.

**Comment by Adithya-copart** [comment]
Looks good so far. No instana related errors in the logs with `INSTANA_DEBUG=1`.
I can see both `puma` and `sidekiq` processes listed within the docker container in our instana dashboard. The sidekiq failures are visible as well as the HTTP traces.

Opened https://github.com/instana/ruby-sensor/pull/148

**Comment by pglombardo** [comment]
#148 merged and released in gem 1.10.1 thanks @Adithya-copart!

https://github.com/instana/ruby-sensor/releases/tag/1.10.1

**Comment by Adithya-copart** [comment]
@pglombardo We tried to use the rubygems version of `1.10.1`.

This piece of code was a bad idea due to https://github.com/rubygems/rubygems/issues/1662#issuecomment-232067212.
https://github.com/instana/ruby-sensor/blob/22cc0e1c0ae77097166d7a8c7d1de86ac89378e9/instana.gemspec#L40

The two options I came across were:
1. Use platform specific gem and tweak the release process.
Ex: [puma](https://github.com/puma/puma/blob/master/Release.md#release-process) does this.
2. Use the [platform =](https://guides.rubygems.org/specification-reference/#platform=) in gemspec.

I came across an example of someone who ran into a similar problem:

PR with Conditional: https://github.com/jnormington/dotdiff/pull/16
PR using `platform =`: https://github.com/jnormington/dotdiff/pull/17

**Comment by pglombardo** [comment]
Ah that's right - I forgot about this bit.  I need to build a local JRuby version with the platform flag set and push that separately to Rubygems...  Give me a bit.

**Comment by pglombardo** [comment]
I added the `platform` flag to the gemspec, built pushed a JRuby version of the gem.

Now on jruby-9.2.7.0, gem install pulls the java version and no Oj gem :-)

<img width="1416" alt="Screen Shot 2019-08-22 at 11 52 37 AM" src="https://user-images.githubusercontent.com/395132/63505198-61d4f280-c4d3-11e9-83ac-2295fa649d2c.png">


Could you give it a try? https://rubygems.org/gems/instana/versions/1.10.1-java

**Comment by Adithya-copart** [comment]
Everything is good now. Thanks Peter!
