### ISSUE TITLE
Support for Elixir?

### ISSUE THREAD

**Issue by mustela** [instana/ruby-sensor#146]
Hey guys! Sorry I know this is not the best place to ask about it. But is there any plan for Elixir or any existing lib we could use? 

Thanks!

**Comment by mmanciop** [comment]
Hi @mustela,

the right place to ask is [Instana's support portal](https://support.instana.com) ;-)
The answer is: we are considering our options, and additional requests like yours help, especially if you provide us with an overview of the libs you use.

Best,
  Michele
