### ISSUE TITLE
reportingUrl is missing when using Instana::Helpers.eum_snippet

### ISSUE THREAD

**Issue by eliten00b** [instana/ruby-sensor#152]
I have the this snippet in the application template of my rails app.

```
::Instana::Helpers.eum_snippet('super-secret-id')
```

But when I check on the Instana Websites dashboard for my application there is an alert that the `reportingUrl` is missing in my code snipped, and yes if I check the HTML it is missing. How I get the `reportingUrl` along with the snippet?

**Comment by pglombardo** [comment]
Hi @eliten00b we just released gem 1.10.2.  Could you give this a try again with this latest gem?

https://github.com/instana/ruby-sensor/releases/tag/1.10.2

**Comment by pglombardo** [comment]
This is confirmed as working so I'm going to close this issue but if anything remains, please feel free to open another issue.
