### ISSUE TITLE
OpenTracing `start_active_span` is not properly supported

### ISSUE THREAD

**Issue by yassenb** [instana/ruby-sensor#193]
`start_active_span` should take a block and (since `0.5.0` of the `opentracing-ruby` gem) return the result of that block. Looking at the code and the tests for it it currently doesn't even execute the block.

**Comment by pglombardo** [comment]
Hi @yassenb - You're right - this Ruby gem hasn't been updated with the latest upstream OT changes yet.  We have OpenTracing updates planned but no ETA as of yet.  

If you want to escalate the update, could you [file a support ticket](https://support.instana.com/hc/en-us/requests/new) with your Instana account details?  With this, the team here can properly track and prioritise the request.

**Comment by hmadison** [comment]
This was resolved back on the 29th of March.
