### ISSUE TITLE
do not print "Starting Instana instrumentation" when INSTANA_DISABLED=true

### ISSUE THREAD

**Issue by breunigs** [instana/ruby-sensor#268]
### Problem Description

This line
https://github.com/instana/ruby-sensor/blob/374e0de39085971c11ebf310ccb858f82d330fdf/lib/instana/base.rb#L42
is logged even if Instana is intentionally disabled. It would be much appreciated if this could also honor `INSTANA_DISABLED` like done elsewhere and adjust the wording slightly to remove any confusion as to whether Instana instrumentation is on or off.
https://github.com/instana/ruby-sensor/blob/374e0de39085971c11ebf310ccb858f82d330fdf/lib/instana.rb#L16

### Minimal, Complete, Verifiable, Example

```bash
export INSTANA_DISABLED=true
cd some-ruby-app
bundle exec rails s
```

### Gemfile.lock

```shell
# instana=1.209.0.pre1
```

### Ruby Version

```shell
not relevant
```

**Comment by hmadison** [comment]
Hi @breunigs 

I've opened #269 to resolve this and should have out later today.

Thanks,
Hunter
