### ISSUE TITLE
[Bug]: Ruby 3.1 support

### ISSUE THREAD

**Issue by neilwilliams** [instana/ruby-sensor#280]
### Problem Description

The latest version of the ruby-sensor gem does not support Ruby 3.1+.

### Minimal, Complete, Verifiable, Example

I have forked the repo and raised a PR there so you can see the changes I think that need to be made:
https://github.com/neilwilliams/ruby-sensor/pull/1/files

We have been running this code in production environments for over 3 months, however, there's some little TODOs I've added where I'd need Instana to help / take over these changes.

We were hoping this would have been addressed officially by now 😄 . I've finally found some time to make this public, so I'm hoping this helps someone at instana address this properly.

### Ruby Version

```shell
Ruby 3.1.2
Rails 7.0.3
```

**Comment by daande** [comment]
We have Instana running in production on Ruby 3.1.3 with Rails 6.1.7 fine.  I actually think this is a issue with ruby-sensor not supporting Rails 7+

**Comment by daande** [comment]
@neilwilliams we submitted a PR https://github.com/instana/ruby-sensor/pull/281 to try and fix this issue....

**Comment by neilwilliams** [comment]
Nice, thanks @daande!

**Comment by neilwilliams** [comment]
Hi @daande / @Ferenc- 

We still get issues running the latest version of the published gem and are still using the forked version I have.

Is anyone able to review this diff please, and let me know if anything jumps out as needing to be done in the released version?
https://github.com/instana/ruby-sensor/compare/master...neilwilliams:ruby-sensor:master

I've pulled in the latest master into my branch, and these are the changes that remain on my branch. 

When using the latest released version we've seen issues with redis and active record - so hopefully you'll see these changes I needed to make a long time ago and realise the released version is missing something? 

I don't really feel comfortable raising a PR (yet at least) as I hacked about in here a long time ago when we moved to Ruby 3.1, to just get things working for us again.

Thanks in advance!

**Comment by Ferenc-** [comment]
@neilwilliams in your diff it appeared that you made changes for Redis 5, which was not fully supported previously. That is now covered in `1.214.0`. I haven't seen anything `active record` specific. Also I am unaware of any issues with `active record`. If you can provide the usual `Minimal, Complete, Verifiable, Example`, then I can take a look.

**Comment by neilwilliams** [comment]
Thanks for your response @Ferenc- - I can confirm version v1.214.0 is looking good for me 🙂 

I'll let you know about the active record issues we saw - and will raise a new issue if there are problems.

Thanks a lot!
