### ISSUE TITLE
OpenTracing: Baggage is not passed/received across the wire on HTTP calls.

### ISSUE THREAD

**Issue by pglombardo** [instana/ruby-sensor#45]
This is an open issue that needs to be implemented in an upcoming release.

We'll follow the golang lead by encoding baggage KVs as HTTP Header/Values on inject/extract.

**Comment by bripkens** [comment]
We should take care to retain interoperability between our various OT implementations. Current Node.js encoding: https://github.com/instana/nodejs-sensor/blob/master/src/tracing/opentracing/Tracer.js#L36-L51 (not saying this is the right way, this is only meant to be a reference).
